version: '3' # docker-composeのバージョンを指定
services: 
  nginx: # サービス名
    container_name: "nginx"
    image: nginx:1.14
    links:
      - php 
  php:
    container_name: "php"
    image: php:7.2-apache
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
  mysqldb:
    platform: linux/x86_64
    image: mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my_testdb
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    volumes:
      - ./docker/db/data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/db/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci